---
sudo: required
language: python
cache: pip
python:
  - '3.6'
service:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
  - pip install ansible molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule --dubug test
after_script:
  - molecule --debug destroy
